"""Transcript logger for saving translation sessions to Markdown files.

Saves Spanish-English translation pairs with timestamps for later review
and English study.
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional


class TranscriptLogger:
    """Logs translation sessions to Markdown files for review and study."""

    def __init__(self, output_dir: Optional[str] = None) -> None:
        """Initialize transcript logger.

        Args:
            output_dir: Directory to save transcripts (default: ~/voicebridge_sessions)
        """
        if output_dir is None:
            output_dir = str(Path.home() / "voicebridge_sessions")

        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Session metadata
        self.session_start = datetime.now()
        self.session_id = self.session_start.strftime("%Y-%m-%d_%H-%M-%S")
        self.translation_count = 0
        self.total_spanish_words = 0
        self.total_english_words = 0

        # Create session file
        self.session_file = self.output_dir / f"session_{self.session_id}.md"
        self._write_header()

    def _write_header(self) -> None:
        """Write Markdown header to session file."""
        header = f"""# VoiceBridge Translation Session

**Date:** {self.session_start.strftime("%Y-%m-%d")}
**Time:** {self.session_start.strftime("%H:%M:%S")}
**Session ID:** `{self.session_id}`

---

"""
        with open(self.session_file, "w", encoding="utf-8") as f:
            f.write(header)

    def log_translation(
        self,
        spanish_text: str,
        english_text: str,
        confidence: float = 0.0,
    ) -> None:
        """Log a translation pair to the session file.

        Args:
            spanish_text: Original Spanish text
            english_text: Translated English text
            confidence: STT confidence score (optional)
        """
        self.translation_count += 1
        timestamp = datetime.now().strftime("%H:%M:%S")

        # Count words
        spanish_words = len(spanish_text.split())
        english_words = len(english_text.split())
        self.total_spanish_words += spanish_words
        self.total_english_words += english_words

        # Format translation entry
        entry = f"""## Translation #{self.translation_count} ({timestamp})

**🇪🇸 Español:** ({spanish_words} palabras)
> {spanish_text}

**🇬🇧 English:** ({english_words} words)
> {english_text}

"""
        if confidence > 0:
            entry += f"*Confidence: {confidence:.0%}*\n\n"

        entry += "---\n\n"

        # Append to file
        with open(self.session_file, "a", encoding="utf-8") as f:
            f.write(entry)

        print(f"[Logger] 📝 Saved translation #{self.translation_count} to {self.session_file.name}")

    def write_summary(self, duration_seconds: float = 0) -> None:
        """Write session summary at the end.

        Args:
            duration_seconds: Total session duration
        """
        if duration_seconds == 0:
            duration_seconds = (datetime.now() - self.session_start).total_seconds()

        minutes = int(duration_seconds // 60)
        seconds = int(duration_seconds % 60)

        summary = f"""
---

# Session Summary

**Duration:** {minutes}m {seconds}s
**Total Translations:** {self.translation_count}
**Spanish Words:** {self.total_spanish_words}
**English Words:** {self.total_english_words}
**Average Spanish:** {self.total_spanish_words / max(self.translation_count, 1):.1f} words/translation
**Average English:** {self.total_english_words / max(self.translation_count, 1):.1f} words/translation

---

*Generated by VoiceBridge* 🌉
"""

        with open(self.session_file, "a", encoding="utf-8") as f:
            f.write(summary)

        print(f"[Logger] ✅ Session summary written to {self.session_file}")
        print(f"[Logger] 📊 Total: {self.translation_count} translations, {minutes}m {seconds}s")

    def get_session_path(self) -> Path:
        """Get the path to the current session file.

        Returns:
            Path to the session Markdown file
        """
        return self.session_file
